import SwiftUI
import UIKit

enum ExportService {
    static func markdown(for lecture: Lecture, note: StudyNote?, cards: [Flashcard]) -> String {
        var lines: [String] = []
        lines.append("# \(note?.title ?? lecture.title)")
        lines.append("")
        if let summary = note?.summary, !summary.isEmpty {
            lines.append("## Summary")
            lines.append(summary)
            lines.append("")
        }
        for heading in note?.headings ?? [] {
            lines.append("## \(heading.heading ?? "")")
            for bullet in heading.bullets ?? [] {
                lines.append("- \(bullet)")
            }
            lines.append("")
        }
        if let terms = note?.keyTerms, !terms.isEmpty {
            lines.append("## Key Terms")
            for term in terms {
                lines.append("- **\(term.term ?? "")**: \(term.definition ?? "")")
            }
            lines.append("")
        }
        if !cards.isEmpty {
            lines.append("## Flashcards")
            for card in cards {
                lines.append("- \(card.question) → \(card.answer)")
            }
            lines.append("")
        }
        lines.append("---")
        lines.append("AI may make mistakes — tap any line to verify against the recording.")
        return lines.joined(separator: "\n")
    }

    static func ankiCSV(cards: [Flashcard]) -> String {
        func escape(_ value: String) -> String {
            let cleaned = value.replacingOccurrences(of: "\"", with: "\"\"").replacingOccurrences(of: "\n", with: " ")
            return "\"\(cleaned)\""
        }
        var rows: [String] = []
        for card in cards {
            rows.append("\(escape(card.question)),\(escape(card.answer))")
        }
        return rows.joined(separator: "\n")
    }

    static func writeTemporary(_ string: String, name: String) -> URL? {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        do {
            try string.write(to: url, atomically: true, encoding: .utf8)
            return url
        } catch {
            return nil
        }
    }

    static func writeTemporary(_ data: Data, name: String) -> URL? {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        do {
            try data.write(to: url)
            return url
        } catch {
            return nil
        }
    }

    @MainActor
    static func pdfData(title: String, note: StudyNote) -> Data? {
        let page = NotePDFPage(title: title, note: note)
        let renderer = ImageRenderer(content: page)
        renderer.scale = 2
        guard let image = renderer.uiImage else { return nil }
        let bounds = CGRect(x: 0, y: 0, width: 612, height: 792)
        let pdfRenderer = UIGraphicsPDFRenderer(bounds: bounds)
        return pdfRenderer.pdfData { context in
            context.beginPage()
            let margin: CGFloat = 40
            let targetWidth = bounds.width - margin * 2
            let ratio = image.size.width / targetWidth
            let drawHeight = image.size.height / ratio
            image.draw(in: CGRect(x: margin, y: margin, width: targetWidth, height: drawHeight))
        }
    }
}

private struct NotePDFPage: View {
    let title: String
    let note: StudyNote

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text(title)
                .font(.system(size: 26, weight: .bold))
            if let summary = note.summary, !summary.isEmpty {
                Text(summary)
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
            }
            ForEach(Array((note.headings ?? []).enumerated()), id: \.offset) { _, heading in
                VStack(alignment: .leading, spacing: 6) {
                    Text(heading.heading ?? "")
                        .font(.system(size: 16, weight: .semibold))
                    ForEach(Array((heading.bullets ?? []).enumerated()), id: \.offset) { _, bullet in
                        Text("• \(bullet)")
                            .font(.system(size: 12))
                    }
                }
            }
            Spacer(minLength: 0)
            Text("Generated by CramJam — AI may make mistakes.")
                .font(.system(size: 9))
                .foregroundStyle(.secondary)
        }
        .padding(48)
        .frame(width: 612, alignment: .topLeading)
        .background(.white)
    }
}
